name:                Core
version:             0.1.0.0
github:              "githubuser/a"
license:             MIT
author:              "Iris"
maintainer:          "0.0@owo.li"
copyright:           "2025 Iris"

extra-source-files:
- README.md


description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5
- containers >= 0.7
- text == 2.1.1
- parsec == 3.1.17.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


executables:
  core-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N


tests:
  core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

